name: "[CD] CHAT BOT VMM"

env:
  IMAGE_NAME: haphuthinh/vikunja-ev:${{ github.ref_name }}-${{ github.sha }}

on:
  push:
    branches:
      - release

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Build Docker image and push to Docker Hub
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME
